### PR TITLE
Implementing enhancement https://github.com/CafepressDev/newrelic-dro…

### PR DESCRIPTION
**Pull request by klnrajareddy**
Addressing issue raised https://github.com/CafepressDev/newrelic-dropwizard-plugin/issues/3

### CODE REVIEW

**Comment by dbaggott** [comment]
Hi @klnrajareddy, thank you for your interest/contribution!

Please update your PR to maintain the logic to default the port to 8081 if not explicitly specified -- that change is not backwards compatible with existing configurations.  For your use case, explicitly specify the port as 80.

Also, how about renaming the `adminContext` to `adminPath` and have it include the leading "/" and default to an empty String if not set?  Then the code becomes a little bit simpler, something like:

```java
    private String readAdminPath(Map<String, Object> properties) {
        return Strings.nullToEmpty((String) properties.get("adminPath"));
    }
```

and

```java
    public HttpHealthCheckProbe build(String host, int port, String adminPath) {
        WebTarget adminWebTarget = ClientBuilder
                .newBuilder()
                .register(new JacksonJsonProvider(new ObjectMapper()))
                .build()
                .target("http://" + host + ":" + port + adminPath);

        return new HttpHealthCheckProbe(adminWebTarget, objectMapper);
    }
```

Finally, please add documentation as to the purpose of the new attribute in the "_comments" section of the plugin.template.  I suggest:

```
'adminPath' attribute is optional.  Use to specify a non-standard admin url path (such as when serving multiple dropwizard applications from the same host/port). For example, if set to "/myApp", health checks would be made using '/myApp/healthcheck'.
```

**Comment by klnrajareddy** [comment]
Thanks a lot Dan.

Take a bow to your comments. You have put all that is required to implement
your suggestions.
I have made a commit with these changes to my master so that you can pull
in these changes.
Please let me know if there is anything else to do here.

Regards,
Raja.

**Comment by dbaggott** [comment]
@klnrajareddy, thanks.  I'll try and release this today for you.

**Comment by klnrajareddy** [comment]
Thanks Dan, this helps a lot.

**Comment by dbaggott** [comment]
@klnrajareddy, this has been deployed as version 1.0.1 and is available in Plugin Central.  The NR deployment process is mildly byzantine and manual (aka error-prone).  Please give it a try and let me know how it goes...

Also, if this plugin ends up being helpful, I encourage you to add a review in Plugin Central.

**Comment by klnrajareddy** [comment]
Sure Dan, this is quite helpful and thanks for releasing it so soon. We
will add review.

Regards,
Raja.

**Pull request merged**
